name: ESettings
version: 1.0.0
main: com.elyther.esettings.ESettings
api-version: '1.21'
author: Elyther
description: Configurable server settings GUI.

commands:
  settings:
    description: Opens the server settings GUI.
    usage: /settings
    aliases:
      - ayarlar

permissions:
  esettings.reload:
    description: Allows reloading ESettings.
    default: op
